create table goods
(
	id int not null,
	title varchar(500) null,
	description text null,
	price int null,
	image varchar(255) null,
	friendly_title varchar(500) null,
	constraint goods_id_uindex
		unique (id)
);

alter table goods
	add primary key (id);
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (9, 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 64, 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 'wd_2tb_elements_portable_external_hard_drive__usb_30');
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (10, 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 109, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 'sandisk_ssd_plus_1tb_internal_ssd__sata_iii_6_gbs');
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (11, 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.', 109, 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 'silicon_power_256gb_ssd_3d_nand_a55_slc_cache_performance_boost_sata_iii_25');
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (12, 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty', 114, 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 'wd_4tb_gaming_drive_works_with_playstation_4_portable_external_hard_drive');
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (13, 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz', 599, 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 'acer_sb220q_bi_215_inches_full_hd_(1920_x_1080)_ips_ultrathin');
INSERT INTO shop.goods (id, title, description, price, image, friendly_title) VALUES (14, 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ', '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag', 1000, 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 'samsung_49inch_chg90_144hz_curved_gaming_monitor_(lc49hg90dmnxza)__super_ultrawide_screen_qled');